FROM node:18-alpine AS build

#Install dependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci

#Copy source & build
COPY . .
RUN npm run build

#Production stage
FROM nginx:alpine

#Remove default nginx content
RUN rm -rf /usr/share/nginx/html/*

#Copy build artifacts
COPY --from=build /app/build /usr/share/nginx/html

#Expose port 80 and serve
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]