"""make user language progress table

Revision ID: 23c9e81fec01
Revises: e1490e20e9f8
Create Date: 2025-07-16 19:01:44.225951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c9e81fec01'
down_revision: Union[str, Sequence[str], None] = 'e1490e20e9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_language_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', name='user_language')
    )
    with op.batch_alter_table('user_language_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_language_progress_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_language', sa.String(), nullable=False))
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('current_language')

    with op.batch_alter_table('user_language_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_language_progress_id'))

    op.drop_table('user_language_progress')
    # ### end Alembic commands ###
